name: CI
on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v1

      - name: Buld code
        run: make

      - name: Test
        run: make test

